### ISSUE TITLE
WBP_UserMenu and WBP_MessengerMenu aren't ideal.

### ISSUE THREAD

**Issue by FreemanMakesGames** [GlowingUser/E2EE#3]
1. Click a BP_User, move mouse into the invisible Button_DetectMouseUnhover, move mouse onto the actual buttons, the menu gets closed.
2. Click a BP_User at the border of the game window, move mouse onto the actual buttons, then directly out of the game window. Move mouse back into the game window, the menu stays open.

**Comment by GlowingUser** [comment]
These menus aren't used anymore.

**Comment by FreemanMakesGames** [comment]
These menus aren't used anymore.
